version: '2.2'
services:
#  api:
#    build:
#      context: docker/dockerfile/part/api
#    environment:
#      - "NODE_ENV=part"
#    expose:
#      - 80
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#    command:  sh -c "npm install --only=prod; npm start"

  tor:
    build:
      context: docker/images/company/tor
    restart: "always"
